@"
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS production_db;
CREATE DATABASE IF NOT EXISTS materials_db;
CREATE DATABASE IF NOT EXISTS units_db;
CREATE DATABASE IF NOT EXISTS reports_db;
"@
