FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["units-service.csproj", "./"]
RUN dotnet restore "units-service.csproj"
COPY . .
RUN dotnet build "units-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "units-service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "units-service.dll"]