// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Оператор производственного оборудования",
                            Name = "Operator",
                            NormalizedName = "OPERATOR",
                            RoleType = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Технолог, настраивающий производственные процессы",
                            Name = "Technologist",
                            NormalizedName = "TECHNOLOGIST",
                            RoleType = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Менеджер производства",
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            RoleType = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Администратор системы",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            RoleType = 4
                        });
                });

            modelBuilder.Entity("AuthService.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d53b80d-9ff7-4b92-badd-2373fc078f37",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 55, 19, 570, DateTimeKind.Utc).AddTicks(928),
                            Email = "admin@mes.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "System",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MES.COM",
                            NormalizedUserName = "ADMIN@MES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENd+BrAfFUDuPXyD2D1/gPwss7BAiCxENKq8xaXuER3Xt83U6rYSMup4qap+fOaOEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52664299-7277-4bd8-96d9-b4944a7bf9a1",
                            TwoFactorEnabled = false,
                            UserName = "admin@mes.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cef96aa4-f2af-435b-b841-d9983f96801e",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 55, 19, 612, DateTimeKind.Utc).AddTicks(6336),
                            Email = "operator@mes.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Operator",
                            LockoutEnabled = false,
                            NormalizedEmail = "OPERATOR@MES.COM",
                            NormalizedUserName = "OPERATOR@MES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO46u2di+IKwpHQA4RqSUSP5Eybeqcc0T6++X0+Ht3cgDXYxfjLsX/w/RDKbS0Q76g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a90baf1c-af67-49ba-80d9-8e85b114521f",
                            TwoFactorEnabled = false,
                            UserName = "operator@mes.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69905db3-5e57-45b3-ba8a-fa489b57cac8",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 55, 19, 655, DateTimeKind.Utc).AddTicks(8476),
                            Email = "tech@mes.com",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Technologist",
                            LockoutEnabled = false,
                            NormalizedEmail = "TECH@MES.COM",
                            NormalizedUserName = "TECH@MES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPtNW+OfXtuDTR4WStgpKXqP+5cvN2m0WQmVifeDNimmLZssQ5vDvVTUejJdVlNtRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5363082a-73c3-4dc0-8d36-f200b9f3c876",
                            TwoFactorEnabled = false,
                            UserName = "tech@mes.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "06cfb7bd-90d9-4dbb-b70d-4b2e409a6312",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 55, 19, 698, DateTimeKind.Utc).AddTicks(7854),
                            Email = "manager@mes.com",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@MES.COM",
                            NormalizedUserName = "MANAGER@MES.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKQR/+fDxltC8Ys5+X6Vj3g0NVFHXQFx3+ApnNN5eXFTgD0QE2TVUFJ5gjXsJ9m8Lg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2173343a-b6b5-41ba-87f5-d1a0a53d29d7",
                            TwoFactorEnabled = false,
                            UserName = "manager@mes.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("AuthService.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
